### ISSUE TITLE
Getting credit ffor work done by other people

### ISSUE THREAD

**Issue by KimBP** [swkim01/openhantek#6]
Hi swkim01
Initially this issue was made to complain about my work pushed to your repo now being part of a huge commit made by you in the Openhantek/openhantek repo. Thus credits to me are lost.

I  feel that is wrong, but from what I can see you actually did send a pull-request containing all individual commits. Don't know how it can happen.

**Comment by swkim01** [comment]
I am sorry about that. Several days ago David who takes control of openhantek repo requested our works to push to it, so I just did one pull request without thinking about that result.
Now the only thing that I can do is to include your contribution in my repo.
I am really sorry again.;-(
